### ISSUE TITLE
Notes are losing changes after synchronizing.

### ISSUE THREAD

**Issue by bwilson** [yuki792/NeighborNote#11]
I have enjoyed using NeighborNote since NixNote stopped working. I have a problem where changes that I make to a note are being deleted - the not reverts back to the way it was immediately after I synchronized.

**Steps to reproduce:**
1: Select an existing note.
2: Synchronize.
3: Edit the note. (Notice that the black sync dot does not appear).
4. Select a different note.
5. Select the first note again. Notice that changes are gone!

**Workaround:**
After synchronizing, always select a different note to refresh the editor before editing.

OS: Ubuntu 15.04.
NeighborNote Version: 0.5.4

I would really appreciate if this could be fixed - it's easy to forget to follow the workaround and frustrating when changes disappear!

Thanks for the great app by the way.

**Comment by yuki792** [comment]
Thanks for using NeighborNote.
I think this issue has been fixed in the new version that I'm developing now.
Could you try it? You can download it below.
https://drive.google.com/file/d/0B1VEmyWJSmlWTWlaazd3Rmd2cEk/view?usp=sharing

Please remove old neighbornote.jar in the installation directory, and put the new one.
Thanks,

**Comment by bwilson** [comment]
Yes, that fixed it, thank you!

-Ben

On Mon, Jul 20, 2015 at 5:11 AM, Takahashi Yuki notifications@github.com
wrote:

> Thanks for using NeighborNote.
> I think this issue has been fixed in the new version that I'm developing
> now.
> Could you try it? You can download it below.
> 
> https://drive.google.com/file/d/0B1VEmyWJSmlWTWlaazd3Rmd2cEk/view?usp=sharing
> 
> Please remove old neighbornote.jar in the installation directory, and put
> the new one.
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yuki792/NeighborNote/issues/11#issuecomment-122836690
> .

## 

 Ben Wilson | Senior Developer
Phone: +1-512-981-7236 | Email: ben.wilson@icsynergy.com
