### ISSUE TITLE
install to Elementary OS

### ISSUE THREAD

**Issue by x35a** [yuki792/NeighborNote#17]
Hi, i'm trying to install NeighborNote on Elementary OS. Seems like the instalation is fine, but the problem is that Elementary OS doesnt allow icons on the desktop end eventually launch icon doesnt appear on desktop. I was trying to launch Neighbor via neighbornote.sh but nothing happend.
Can you please advise how can i launch neighbornote alternatively ? Thanks in advance.

**Comment by rosivanov** [comment]
@
