### ISSUE TITLE
Possible hang when switching between notes

### ISSUE THREAD

**Issue by jeffbuhrt** [yuki792/NeighborNote#2]
NeighborNote seems to have some (other?) display/hang issues, clicking on a few
various notes, NeighborNote locked and I had to kill it.

[So far I haven't found the sequence again. I can make NN take a lot of processor and wait ~5-10sec now.]

$  ~/neighbornote-0.5.2/neighbornote.sh
QtJambiInternal.buildMetaData: Writer for property
content takes a type which is incompatible with reader's return type.
log4j:WARN No appenders could be found for logger
(org.apache.http.impl.conn.SingleClientConnManager).
log4j:WARN Please initialize the log4j system properly.
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
X Error: BadLength (poly request too large or internal Xlib length error) 16
  Extension:    138 (RENDER)
  Minor opcode: 4 (RenderCreatePicture)
  Resource id:  0x2a
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
^C

**Comment by yuki792** [comment]
I'm terribly sorry for late fixing. It's already been past a half year.
Now, I have fixed this issue. I'll release the latest version of NeighborNote in the near future.

Thanks,
