### ISSUE TITLE
Cannot download from homepage - too much JavaScript magick?

### ISSUE THREAD

**Issue by fnl** [yuki792/NeighborNote#7]
When I click on "agree and download", clicking on the presented download buttons for the installers does nothing.

http://puma.cis.ibaraki.ac.jp/products/neighbornote/en/download.html

(Workaround, by the way, is to manually reconstruct the URL of the archive to download from the attributes on the buttons.)

**Comment by yuki792** [comment]
Certainly, JavaScript is used to open the file list.
But, I just used slideToggle of JQuery.
I think every browser can use this function unless disabling JavaScript.

And people can also download NeighborNote from [SrouceForge.jp](http://sourceforge.jp/projects/neighbornote/releases/).

thanks,

**Comment by fnl** [comment]
Sure, no problem, I have it already, after all. Nice work to you and the guy who wrote nixnotes!

I just thought you might want to be aware of this issue, as it seemed to me it would be in your best interest to make it as painless as possible to download your software. That is, instead of placing irregular behavior on a button, have a clean, real link: It wasn't the case that I don't have JS enabled (otherwise I would not even have seen the button in the first place), but rather, that I use measures to protect myself from malicious sites by disabling irregular behavior, and not just bluntly disable all JS.

Whatever - I'll close this then, as I don't really mind.
