### ISSUE TITLE
No notification icon

### ISSUE THREAD

**Issue by Bjarno** [yuki792/NeighborNote#9]
There is no notification icon on Ubuntu 14.04 LTS. After enabling it in settings (go to tray on minimize) and clicking close, I see no icon.

I'm unable to restart the application, as it will try to connect again with an already opened database.

Possible fixes:
- Fix the icon
- When opening NeighbourNote twice, show the first window and stop the new application instance.

**Comment by yuki792** [comment]
This issue is caused by Unity's limitation.
Please see #6.

Regards,

**Comment by Bjarno** [comment]
Didn't see it, as it was closed, so I thought it was not yet known. Will close this one too.

Thanks anyway for your response.

**Comment by yuki792** [comment]
I'll add this workaround in the tutorial later. Thanks,
